### ISSUE TITLE
mount.core reload-prevention for clojure.tools.namespace isn't working

### ISSUE THREAD

**Issue by krajj7** [tolitius/mount#106]
Mount contains code to prevent clojure.tools.namespace from reloading its vars:

https://github.com/tolitius/mount/blob/c5f3e4cdf81d3b632a463a1db19ae3f73c0ad2c9/src/mount/core.cljc#L20-L22

But this is not effective, because `::load` in this context expands to `:mount.core/load`, while `clojure.tools.namespace` is looking for keywords in its own `clojure.tools.namespace.repl` namespace ([here](https://github.com/clojure/tools.namespace/blob/bb9d7a1e98cc5a1ff53107966c96af6886eb0f5b/src/main/clojure/clojure/tools/namespace/repl.clj#L33) `::load` expands to `:clojure.tools.namespace.repl/load`)

So the code should be changed to:
```clojure
(alter-meta! *ns* assoc :clojure.tools.namespace.repl/load false)
```

This probably isn't a problem for most projects using c.t.n.r/refresh. I accidentally set up a project in a way that it refreshed the libraries including mount, but I'm not even sure how since it usually doesn't do that.
For testing it can be done by calling `c.t.n.repl/set-refresh-dirs` directly on a local path to mount/core.cljc file and then calling `c.t.n.repl/refresh-all`, which shows whether mount.core is reload-protected or not.

**Comment by tolitius** [comment]
interesting, yea, definitely makes sense. not sure how it slipped through. want to PR it?

**Comment by krajj7** [comment]
OK I will make a PR.

**Comment by krajj7** [comment]
I made the PR fixing one occurrence of this problem, but only just noticed it is also present in almost all test namespaces in mount and in other repos as well (eg. [mount-up](https://github.com/tolitius/mount-up/blob/1c152514896cce8bbf3398e7aee2ed9ff29a7bd5/src/mount_up/core.clj#L8-L9), [yurt](https://github.com/tolitius/yurt/blob/0e997bb52cc1c6fd9171d71fc368e7de55d8f206/dev/clj/utils/logging.clj#L9)). 

It seems to me that in mount `mount.core` is the only namespace where reload prevention makes sense, although I'm not sure why it was used in the tests so maybe I'm missing something.

**Comment by tolitius** [comment]
thanks for the pull request!

yea, I'd need to clean it up from `mount-up` / `yurt` and rethink test applications. one reason it is needed in some of the tests was to make sure the fixtures are not wiped when _testing for_ refresh / reload.
