### ISSUE TITLE
using mount.core instead of just mount would be more idiomatic

### ISSUE THREAD

**Issue by yogthos** [tolitius/mount#11]
it's a small nitpick, but it's a bit more idiomatic to create a core namespace

**Comment by tolitius** [comment]
I hope it is _"small"_ :) 

For some reason `core` for the sake of `core` never sat well with me. I agree that most of the iconic projects use it, but.. what I noticed, once additional features are added to the project, `core` goes away, or becomes really small (i.e. [1](https://github.com/reagent-project/reagent/blob/master/src/reagent/core.clj), [2](https://github.com/omcljs/om/blob/master/src/main/om/core.clj)), and real names pop up, or [projects](https://github.com/yogthos/Selmer/tree/master/src/selmer) :) just start without `core` all together, which I think is quite clean.

**Comment by yogthos** [comment]
The [official naming convention](http://clojure.org/libs) as well as the [style guide](https://github.com/bbatsov/clojure-style-guide#naming) suggest that namespaces should use at least two parts in the name. I figure it's good for a library to follow common conventions. :)

**Comment by tolitius** [comment]
> A lib name is a symbol that will typically contain two or more parts separated by periods

and

> it's good for a library to follow common conventions

sound convincing... but :sad: :) I don't understand why can't a library "be named by its name"

**Comment by yogthos** [comment]
I think the original intent was to make namespace collisions less likely, and then people started using `lib.core` as a convention when there wasn't an obvious second symbol for the name.

One advantage of this convention is that it makes it easy to find the entry point when looking through the code. In the om/reagent examples the `core` gives a starting point to trace from for example.

**Comment by tolitius** [comment]
makes sense, but still feels off. "wasn't an obvious second symbol for the name" usually occurs when something is wrong with naming :)

but again, I agree. this is not huge to fight the system. and adding `.core` most likely would only help rather than hurt, since it is expected.

**Comment by yogthos** [comment]
yeah pretty much :)

**Comment by tolitius** [comment]
found an interesting :) related [commit](https://github.com/tonsky/datascript/commit/31793ab1048213f91f367c35c4e1199c91a8a30f):

> _Note:_ Since DataScript 0.13 **main namespace to include is `datascript.core`**, not `datascript`. This was done because usage of top-level namespaces is discouraged and even generates a warning in CLJS. Old `datascript.core`, if you were using it, was renamed to `datascript.db`

**Comment by yogthos** [comment]
looks like many projects end up going through this :)

**Comment by yogthos** [comment]
and I've integrated mount with Luminus, it fits like a glove. Once the new version with the API update is up on Clojars I'd like to push out a new version of Luminus using it.

The main icky part for me was having global defs for things like db connections, and since I'm trying to be beginner friendly Component was out. With Mount I can just replace my connection var with one using defstate and it's beautiful. :)

**Comment by tolitius** [comment]
this is great, thank you for the feedback! :)

**Comment by yogthos** [comment]
Any chance of a new release with the change, I'd like to push out a new luminus release with mount integrated and I want to target the new API from the get go.

**Comment by tolitius** [comment]
sure: [0.1.3](https://clojars.org/mount/versions/0.1.3)

**Comment by yogthos** [comment]
:+1:
