### ISSUE TITLE
documentation: difference with Integrant

### ISSUE THREAD

**Issue by jaimesangcap** [tolitius/mount#119]
There is already a docs about the difference of mount with `component` library.

I'm wondering about the difference with `integrant` and I came across this reddit post https://www.reddit.com/r/Clojure/comments/5gvhi2/integrant_an_alternative_to_component_and_mount/

What is your thought about the difference of `mount` and `integrant`? 

I think putting it in the docs would be very helpful.

**Comment by tolitius** [comment]
sorry, just saw it
have not used integrant in production, it is definitely a step in the right direction from component
and I did discuss it with the integrant author a little bit [here](https://www.reddit.com/r/Clojure/comments/5gvhi2/comment/davsmqc/?utm_source=share&utm_medium=web2x&context=3) on reddit

there are more interesting solutions, such as [clip](https://github.com/juxt/clip) for example

at the end of the day many ideas are always better than one.
I do use mount for many years now, throughout many different projects and a few completely different teams / mindsets, and it works great for us. I am sure integrant works great for other people as well.

**Comment by jaimesangcap** [comment]
Thank you for taking the time to respond. I was actually listening to your ClojureScript podcast episode yesterday, and when you said "don't give it 5 minutes, give it 5 months", that sticks with me. I think I just have to spend some time to try these tools to get better judgement. I find other tools have higher ceremony for my use case. For now I'm enjoying mount, thank you for sharing it to the world. Thank you for the references as well, something to learn more about :)
