### ISSUE TITLE
Please consider providing deps.edn to support consuming from git

### ISSUE THREAD

**Issue by ieugen** [tolitius/mount#131]
Hello,

Please consider providing deps.edn file to allow consumption via git for the library.

It will make it easier to test things like https://github.com/tolitius/mount/pull/130  before a release is cut. 

Thank you,

**Comment by rome-user** [comment]
This isnt needed for git consumption. You can use Leiningen plugins like `lein-git-down` or, in the case of deps.edn, set `:deps/manifest` then you can use the project as normal (see https://clojure.org/reference/deps_edn#_shared_dep_attributes)

**Comment by ieugen** [comment]
Thanks
