### ISSUE TITLE
Clj-kondo warning on defstate deref.

### ISSUE THREAD

**Issue by Kaspazza** [tolitius/mount#136]
When doing deref on defstate variable clj-kondo throws warning that the deref is done on the return value. Not understanding it is an atom.

```code
(defstate routes
          :start
          (do ["a" "b"]) )
          
  @routes 
 
```
Message: "Expected: deref, received vector. [type-mismatch]

or 
```code
(defstate routes
          :start
          (prn "hello"))
          
  @routes 
 
```
Message: "Expected: deref, received nil. [type-mismatch]

**Comment by tolitius** [comment]
thanks for reporting this and #135 

I don't use `clj-kondo`, and I use vim, so could not really test it

"`clj-kondo` support" was introduced by these commits: [1](https://github.com/tolitius/mount/commit/098b56d14fef2284fedc4a9d061fe3266b4ef26c), [2](https://github.com/tolitius/mount/commit/5df6c941f786fe5c6a4b7b4841e700a553437beb), [3](https://github.com/tolitius/mount/commit/4065f5df368893dcb4546fd80f573ee9f9226f85)

@NoahTheDuke, @rajcspsg can you help?

_if we are unable to solve this, I would need to back our those commits, so it does not impact others_

**Comment by NoahTheDuke** [comment]
Yeah I can fix this tomorrow.

**Comment by tolitius** [comment]
@NoahTheDuke 
did you have a chance to look at it?

let me know if you did not, I'll revert the "`clj-kondo`" commits for now until you have time

**Comment by NoahTheDuke** [comment]
@tolitius my apologies for the delay, I've put up a new PR to handle this and the other issue related to clj-kondo
