### ISSUE TITLE
Pass data to start functions

### ISSUE THREAD

**Issue by sstuddard** [tolitius/mount#2]
I frequently write command line programs that rely heavily on command line arguments for parameters. This is just one use case, but it would be great to somehow pass arbitrary data to the start functions like so:

```
(defn -main
  [& args]
  (mount/start {:config_file (first args)}))
```

**Comment by kenrestivo** [comment]
I'll need this as well.  In particular

``` sh
java -jar someuber.jar config.edn
```

The config file arg will need to be passed through the state. Components does this well, but of course I'm bumping into a lot of the same problems with components that led you to write mount.

**Comment by kenrestivo** [comment]
Nevermind, I just thought of a way to do it:

``` clojure
(defonce conf (atom {}))

(defn -main
  [& [conf-file-arg & _]]
  (reset! conf (-> conf-file-arg slurp read-edn)))
;; do the settings management/storage outside of mount
```

Then the conf is present. Untested, but this will probably work for me. Thanks for writing mount!

**Comment by tolitius** [comment]
that's definitely needed.

I was thinking of doing:

``` clojure
(defn -main [& args]
  (mount/start args))
```

where these args will be accessible in other states / functions via mount:

``` clojure
(defstate config :start (parse-args (mount/args)))
```

where `parse-args` is the app's custom fn.

What do you guys think?

**Comment by kenrestivo** [comment]
I like it. 

By the way, I remember reading hints some years ago that one of the reasons that components didn't leverage the ns system for dependencies, is that the ns macro is kind of complected and has some issues and gotchas.  I don't remember the details; bronsa might know.

**Comment by kenrestivo** [comment]
And, I've just used mount in a project. I did a simpler hack around args, which was basically:

``` clojure
(defonce args-atom [])

(defstate conf :start (load-conf-file (-> args-atom deref first)))

(defn -main [& args]
  (reset! arg-atom args)
  (mount/start))
```

Works for me.

I will in the next day or two post a small project that uses mount. 

Args support would make it easier to make reusable modules.

I can't imagine going back to component though.

**Comment by sstuddard** [comment]
It would be great to keep it as simple as possible and keep mount ignorant of the data. mount/start takes a something, and passes it to the start function. That leaves it entirely up to the implementation what that data is, whether it's an atom, a map, a vector, whatever.

Is that what you're proposing? mount/args would return that thing?

**Comment by tolitius** [comment]
yep, `(mount/args)` just returns `args` (or "parsed" args).

here is [what I put together](https://github.com/tolitius/mount/blob/master/doc/runtime-arguments.md#passing-runtime-arguments).

the only difference from what I proposed above is starting with arguments is not `(mount/start args)`, but:

``` clojure
(defn -main [& args]
  (mount/start-with-args args))
```

The reason is `(mount/start)` can _optionally_ start a part of the app (only certain states):

``` clojure
(mount/start #'app/conf #'app.db/conn #'app.aws/some-sqs)
```

and I don't want to overload it with args. I believe `(start-with-args args)` is a simple enough solution.

Let me know what you guys think.

**Comment by sstuddard** [comment]
I tried to imagine how something like the following could work but couldn't come up with something that wouldn't be complicated.

```
(defstate conn :start (create-conn host user password)
               :stop (disconnect conn))
```

where the parameters are somehow pulled from the arguments automagically.

start-with-args is a good place to start, and it makes sense why it's a different function.

**Comment by tolitius** [comment]
@sstuddard,

``` clojure
(defstate conn :start (create-conn host user password))
```

with "magically" pulling values from `args` is no complicated _to do_, but I feel it is not straightforward to work with. Here is what I mean:

``` clojure
(:require [app.config :as config])

;; ... now, let's say one of the runtime `args` names is "config"
(defstate conn :start (create-conn config))
```

which `config` do we pass to `create-conn`: the top level one or the one in args?

---

If you don't think `(mount/args)` is clean enough to pass to states, you can always wrap it in another namespace:

``` clojure
(ns app.config
  (:require [mount :as m]))

(defn config []
  (m/args))          ;; they can also be parsed here

(defn db-config []   ;; pull out specific sub configs
  (-> m/args :db))
```

then

``` clojure
(:require 
  [mount :refer [defstate]]
  [app.config :refer [db-config]])

(defn create-conf [{:keys [host user password]}]
  ...)

(defstate conn :start (create-conn db-config))
```

**Comment by sstuddard** [comment]
That's a great idea, it's clean without complicating mount itself. 

Should this be closed now?

**Comment by tolitius** [comment]
yep, the code is in the [0.2.0-SNAPSHOT](https://clojars.org/mount/versions/0.2.0-SNAPSHOT)

**Comment by tolitius** [comment]
not sure why I went with `0.2.0`, fixed.
it is in [0.1.1](https://clojars.org/mount/versions/0.1.1) release, as it should have been.

**Comment by kenrestivo** [comment]
If it were possible to hug 100 lines of Clojure, I would hug this.

You've saved me from Component hell. Thank you very much!

**Comment by tolitius** [comment]
@kenrestivo very welcome, glad it works for you! :)
