### ISSUE TITLE
Error of plain value as `start` form

### ISSUE THREAD

**Issue by xhh** [tolitius/mount#20]
When I tried to use a plain value like a map as the `start` form, an error is thrown:

``` clojure
boot.user=> (defstate config :start {:init :state})
nil
boot.user=> (start)
21:21:30.007 [nREPL-worker-16] INFO  mount.core - >> starting..  config

 java.lang.RuntimeException: could not start [config] due to
clojure.lang.ArityException: Wrong number of args (0) passed to: PersistentVector
```

In [defstate](https://github.com/tolitius/mount/blob/master/src/mount/core.clj#L38), should this

``` clojure
:start `(fn [] (~@start)) 
```

be changed to this?

``` clojure
:start `(fn [] ~start) 
```

**Comment by aroemers** [comment]
I think this would indeed be better, together with `trampoline`. That way, both of the following is possible:

``` clj
(defn- start-foo [] {:init :state})

(defstate foo :start start-foo)
```

and

``` clj
(defstate foo :start {:init :state})
```

Just my two :moneybag:

**Comment by tolitius** [comment]
@xhh, @aroemers: no disagreement here :) Thank you, it makes it easier to make that decision when I know other people want it.

The reason it was not done before is "fns with arguments": I just could let this clean syntax go (mostly in my head):

``` clojure
(:start (fun args))
```

but I agree it makes sense to sacrifice for `#`, it is now:

``` clojure
(:start #(fun args))

(:start fun)

(:start 42)
```

changes are in [0.1.5 branch](https://github.com/tolitius/mount/tree/0.1.5#value-of-values)

**Comment by aroemers** [comment]
Actually, you didn't sacrifice `:start (fun args)` at all :) That still works, as you [wrap](https://github.com/tolitius/mount/blob/339d79e50803800b9a59f6ea120bfddf638d2a80/src/mount/core.clj#L38) the form in a function :smile: So maybe you'd want to revert your examples again?

**Comment by tolitius** [comment]
oh.. :) you are right. I did not think of that. Just automatically assumed that losing `~@fun` will lose the ability to have a function as a state value.

Yea, I would need to revert all the `#(` examples. Although now, having me going through #18, it is good that I made this omission :)
