### ISSUE TITLE
Any plans for a 0.1.0 release?

### ISSUE THREAD

**Issue by kenrestivo** [tolitius/mount#3]
I'd like to use this in a releasable uberjar, but the SNAPSHOT thing worries me.

Are there plans on the horizon for a 0.1.0 release?

**Comment by tolitius** [comment]
@kenrestivo sure, `0.1.0` is released: https://clojars.org/mount

there are also some [uberjar thoughts](https://github.com/tolitius/mount/blob/master/doc/uberjar.md#creating-reloadable-uberjarable-app), hope you'll find it helpful
