### ISSUE TITLE
Clojure version requirements need to be documented

### ISSUE THREAD

**Issue by collinalexbell** [tolitius/mount#32]

**Comment by SlightlyCyborg** [comment]
Here is my project.clj

    (defproject mission_match "0.1.0-SNAPSHOT"
      :description "FIXME: write description"
      :url "http://example.com/FIXME"
      :license {:name "Eclipse Public License"
                :url "http://www.eclipse.org/legal/epl-v10.html"}
      :dependencies [[org.clojure/clojure "1.6.0"]
                     [hiccup "1.0.5"] 
                     [ring "1.4.0"]
                     [mount "0.1.7"]
                     [com.novemberain/monger "3.0.0-rc2"]]                   
      :plugins  [[lein-ring "0.8.11"]]
      :ring  {:handler mission-match.core/main-handler}
    )

After I run `lein deps` and then `lein repl` and then `(require '[mount.core :refer [defstate]])` I get the response `FileNotFoundException Could not locate mount/core__init.class or mount/core.clj on classpath:   clojure.lang.RT.load (RT.java:443)`

**Comment by tolitius** [comment]
@SlightlyCyborg, good point: [noted](https://github.com/tolitius/mount/blob/master/README.md#clojure-version)
