### ISSUE TITLE
Error in https://clojars.org/repo/mount/mount/maven-metadata.xml

### ISSUE THREAD

**Issue by paulrd** [tolitius/mount#33]
The clojars repository has the following file:
https://clojars.org/repo/mount/mount/maven-metadata.xml

It has a bug in it that makes lein-ancient fail. It references a version (0.2.0-SNAPSHOT) that does not exist in clojars.org or maven.org and therefore causes lein-ancient to fail to pick up the latest snapshot of mount (currently 0.1.8-SNAPSHOT).

here is the relevant section of the file:

<version>0.1.0-SNAPSHOT</version>
<version>0.1.0</version>
<version>0.2.0-SNAPSHOT</version>   ;; <- delete this line
<version>0.1.2</version>
<version>0.1.3-SNAPSHOT</version>
<version>0.1.1</version>

**Comment by tolitius** [comment]
thanks, I submitted [an issue](https://github.com/clojars/clojars-web/issues/447) on clojars.

**Comment by tolitius** [comment]
@paulrd, Toby fixed the metadata ([clojars issue](https://github.com/clojars/clojars-web/issues/447)). 
Let me know, feel free to reopen this, if you still see the problem.
