### ISSUE TITLE
lein test mount.test.fun-with-values fails

### ISSUE THREAD

**Issue by paulrd** [tolitius/mount#34]
I was curious why the semantics of defstate had @ (deref) in the test file. Those semantics don't seem to work as described. lein test mount.test.fun-with-values fails as expected, but lein test passes (running complete test suite). There seems to be some test state that I'm not aware of. Is this a bug or a feature?

**Comment by paulrd** [comment]
I see now that mount.test.var.fun-with-values has the expected semantics. Why the two different files / semantics?

**Comment by tolitius** [comment]
@paulrd good question :)

mount supports Clojure and ClojureScript, but for the reasons [described here](https://github.com/tolitius/mount/blob/master/doc/clojurescript.md#managing-state-in-clojurescript), in case an application needs to support both at the same time, mount needs to be switched to `(mount/in-cljc-mode)` mode. In this mode it supports both Clojure and ClojureScript with consistent API across both.

The only difference between the default mount mode and `cljc` is that in case of `cljc` states need to be derefed (i.e. `@`) before used. Tests for `fun-with-values` are there for both modes.

Let me know if this clears it up, or you have more questions.

**Comment by paulrd** [comment]
Ah! Thanks.
