### ISSUE TITLE
Readme: start and stop take vars, not namespaces

### ISSUE THREAD

**Issue by Peeja** [tolitius/mount#35]
In the Readme, under [Start and Stop Parts of Application](https://github.com/tolitius/mount#start-and-stop-parts-of-application), it says that `start` and `stop` optionally take "namespaces". But they appear to take vars, no?

Can they also take namespaces, and will they then apply to every `defstate` in the namespace? Or is that just a typo?

**Comment by tolitius** [comment]
@Peeja, good point, thanks. [fixed](https://github.com/tolitius/mount/blob/master/README.md#start-and-stop-parts-of-application)
