### ISSUE TITLE
Mount Reports Removed defstates

### ISSUE THREAD

**Issue by paulrd** [tolitius/mount#42]
I noticed that if I delete a defstate and then do a clojure.tools.namespace.repl/refresh, calling (mount/start) still reports that the old defstate is being started even though it is not. I have to restart the repl to get (mount/start) to report what is actually happening.

**Comment by tolitius** [comment]
@paulrd ah.. good point. might need to check (i.e. `(when (resolve 'state) ... )`) the state existence on lifecycle (start/stop/resume/suspend) events. The tricky part is to make it work consistently in ClojureScript :) will give it more thought, thanks for finding it.

**Comment by tolitius** [comment]
@paulrd I'd still like to keep it open until I can test the need for it in ClojureScript, but let me know if `0.1.9-SNAPSHOT` fixes it for you.

**Comment by tolitius** [comment]
here are some docs about [cleaning up deleted states](https://github.com/tolitius/mount#cleaning-up-deleted-states)

**Comment by tolitius** [comment]
closing this. will reopen in case there are problems reporting cleaned states on the ClojureScript side.
