### ISSUE TITLE
Is there a way to get the status of current services?

### ISSUE THREAD

**Issue by ftravers** [tolitius/mount#49]
Be nice to have a status command or something like that.

**Comment by tolitius** [comment]
would something like this work for you?

``` clojure
dev=> (require '[mount.tools.graph :as graph])

dev=> (graph/states-with-deps)
({:name "#'app.conf/config", 
  :order 1, 
  :status #{:started}, 
  :deps #{}}
 {:name "#'app.db/conn",
  :order 2,
  :status #{:started},
  :deps #{"#'app.conf/config"}}
 {:name "#'app.www/nyse-app",
  :order 3,
  :status #{:started},
  :deps #{"#'app.conf/config"}}
 {:name "#'app.example/nrepl",
  :order 4,
  :status #{:started},
  :deps #{"#'app.www/nyse-app" "#'app.conf/config"}})
```

a bit more details [here](https://github.com/tolitius/mount/issues/12#issuecomment-167150505)

**Comment by ftravers** [comment]
that looks great!  let me give it a spin... thank you!

On Tue, Feb 23, 2016 at 4:48 PM, Anatoly notifications@github.com wrote:

> would something like this work for you?
> 
> dev=> (require '[mount.tools.graph :as graph])
> 
> dev=> (graph/states-with-deps)
> ({:name "#'app.conf/config",
>   :order 1,
>   :status #{:started},
>   :deps #{}}
>  {:name "#'app.db/conn",
>   :order 2,
>   :status #{:started},
>   :deps #{"#'app.conf/config"}}
>  {:name "#'app.www/nyse-app",
>   :order 3,
>   :status #{:started},
>   :deps #{"#'app.conf/config"}}
>  {:name "#'app.example/nrepl",
>   :order 4,
>   :status #{:started},
>   :deps #{"#'app.www/nyse-app" "#'app.conf/config"}})
> 
> a bit more details here
> https://github.com/tolitius/mount/issues/12#issuecomment-167150505
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/tolitius/mount/issues/49#issuecomment-187991907.

## 

PGP Key ID: 3DB603C0

**Comment by tolitius** [comment]
sure, let me know if that works for you. even though mount has it for some time now, I have not document this, since there are a couple of caveats:
- it does not work for ClojureScript, since it relies on namespace APIs
- dependencies are really namespace bound: i.e. dependencies between namespaces

I think the ClojureScript point maybe addressed with ClojureScript Bootstrap with an application running in a _none_ `:advanced` mode.

But besides those two it should provide some application status visual.

**Comment by ftravers** [comment]
right...good points.

On Tue, Feb 23, 2016 at 5:02 PM, Anatoly notifications@github.com wrote:

> sure, let me know if that works for you. event though mount has it for
> some time now, I have not document this, since there are a couple of
> caveats:
> - it does not work for ClojureScript, since it relies on namespace APIs
> - dependencies are really namespace bound: i.e. dependencies between
>   namespaces
> 
> I think the ClojureScript point maybe addressed with ClojureScript
> Bootstrap with an application running in a _none_ :advanced mode.
> 
> But besides those two it should provide some application status visual.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/tolitius/mount/issues/49#issuecomment-187994907.

## 

PGP Key ID: 3DB603C0

**Comment by tolitius** [comment]
I am closing this, reopen if you have more questions about `status of current services`
