### ISSUE TITLE
failed to initalize with boot version 2.6.0

### ISSUE THREAD

**Issue by jlgeering** [tolitius/mount#54]
$ boot repl

works fine with boot 2.5.2 (except for some deprecation warnings), but with boot version 2.6.0, I get:

```
     clojure.lang.ExceptionInfo: template already refers to: #'boot.core/template in namespace: adzerk.boot-reload
    data: {:file "adzerk/boot_reload.clj", :line 1}
java.lang.IllegalStateException: template already refers to: #'boot.core/template in namespace: adzerk.boot-reload
                                        ...
                         clojure.core/refer                          core.clj: 4098
                                        ...
                         clojure.core/apply                          core.clj:  632
                      clojure.core/load-lib                          core.clj: 5730
                                        ...
                         clojure.core/apply                          core.clj:  632
                     clojure.core/load-libs                          core.clj: 5749
                                        ...
                         clojure.core/apply                          core.clj:  632
                       clojure.core/require                          core.clj: 5832
                                        ...
adzerk.boot-reload/eval1054/loading--auto--                   boot_reload.clj:    1
                adzerk.boot-reload/eval1054                   boot_reload.clj:    1
                                        ...
                       clojure.core/load/fn                          core.clj: 5866
                          clojure.core/load                          core.clj: 5865
                                        ...
                      clojure.core/load-one                          core.clj: 5671
                   clojure.core/load-lib/fn                          core.clj: 5711
                      clojure.core/load-lib                          core.clj: 5710
                                        ...
                         clojure.core/apply                          core.clj:  632
                     clojure.core/load-libs                          core.clj: 5749
                                        ...
                         clojure.core/apply                          core.clj:  632
                       clojure.core/require                          core.clj: 5832
                                        ...
                           boot.user/eval70  boot.user1854421973038905773.clj:    9
                                        ...
                         boot.main/-main/fn                          main.clj:  196
                            boot.main/-main                          main.clj:  196
                                        ...
                           boot.App.runBoot                          App.java:  399
                              boot.App.main                          App.java:  488
                                        ...
                                  Boot.main                         Boot.java:  258
```

**Comment by tolitius** [comment]
thanks for reporting this. can you try `mount-0.1.11-SNAPSHOT`?

**Comment by tolitius** [comment]
`mount-0.1.11-SNAPSHOT` should have the fix. will close it, feel free to reopen if you have additional questions.

**Comment by jcc2303** [comment]
Hi tolitius,

I am on linux, and really new in clojure and boot.
where I have to edit use mount-0.1.11-SNAPSHOT ?
and / or where I have to read to know that. 

thanks in advance!

**Comment by tolitius** [comment]
@jcc2303 this issue is about cloning mount source code and running it using boot. In which case, if you have boot `2.6.0` installed on your system / computer you should clone mount and check out the `0.1.11` branch before doing `boot repl`.

if you just use mount within your project (as a dependency), add `[mount "0.1.11-SNAPSHOT"]` and see if it works for you.

I guess the question is "what are you trying to do?"

**Comment by jcc2303** [comment]
thanks @tolitius 

I was trying this
[Clojurescript application template using Boot](https://github.com/martinklepsch/tenzing)

I was reading and I tried to edit build.boot and add the lines below
(set-env!
 :dependencies '[ . . .
                [mount            "0.1.11-SNAPSHOT"]

but nothing  when I tried to run 

> boot dev

by now I downgrade boot, I create a boot.properties and put BOOT_VERSION=2.5.2

**Comment by tolitius** [comment]
are you using mount as a dependency for your sample application? if yes, there is nothing else you need to do from mount's side, since mount itself brings no dependencies.

I'll close this issue as your use case a bit different from the one reported.

We can continue discussing this on [#mount](https://clojurians.slack.com/messages/mount/) slack channel, or you can try [#boot](https://clojurians.slack.com/messages/boot/) slack channel, since it seems that your questions is really about boot than mount.

**Comment by onetom** [comment]
This was a `boot-reload` issue, which was fixed in [this commit](https://github.com/adzerk-oss/boot-reload/commit/b424f5da817293eabfb18c5dc0fbe575173e3fa3).

**Comment by tolitius** [comment]
@onetom: great, thanks for the intel
