### ISSUE TITLE
any reason why mount/start accepts a collection and mount/stop does not?

### ISSUE THREAD

**Issue by jiangts** [tolitius/mount#69]
Recently ran into a silly problem where I passed mount/stop a vector of states and none of the states stopped. Was a bit of a surprise to me because mount/start accepts a collection.

Not that it's a big deal, but wondering if there's any reason for a non-congruent API.

**Comment by tolitius** [comment]
silly but a valid issue :)

fixed in the latest `0.1.11-SNAPSHOT`.

let me know if it works for you.
