### ISSUE TITLE
start-without/stop-except misbehave when states = all states

### ISSUE THREAD

**Issue by oahner** [tolitius/mount#81]
So, as one would expect, `start-without` and `stop-except`, when called with all states available in the system, call `start`/`stop` with an empty list, which is normally a noop.

Unfortunately the actual call is made with `apply`, which converts the empty list to a seq, which converts the empty seq to nil, which is what `start` and `stop` receive as `states` (as if they were called with no arguments) and start/stop every state in the system.

**Comment by tolitius** [comment]
ah. good catch, thanks.

should be fixed in `0.1.12-SNAPSHOT`. let me know if it works for you.

when would you `start-without` / `stop-except` ALL?

**Comment by oahner** [comment]
It works!

I stumbled upon that behavior on a project that had two states where one (the webserver) doesn't need to be restarted on reset and I had temporarily commented out the other. End result: the webserver state was suddenly getting restarted on reset.

**Comment by tolitius** [comment]
ah.. makes sense. thanks for bringing it up
