### ISSUE TITLE
start-with-states only works with functions

### ISSUE THREAD

**Issue by didibus** [tolitius/mount#82]
I've noticed that when using `start-with-states`, you have to wrap all yous start and stop states in a function. This is different from the defstate macro, which support scalars and literals and vars, etc.

**Comment by tolitius** [comment]
the idea is that in case you need "scalars and literals and vars, etc." you can use [start-with](https://github.com/tolitius/mount#swapping-states-with-values) instead.

you would normally use [start-with-states](https://github.com/tolitius/mount#swapping-states-with-states) when you _need_ functions: i.e. to create something and then to _destroy_ it.

this is also consistent with `swap` vs. `swap-states` when you [compose states](https://github.com/tolitius/mount#composers-toolbox).

**Comment by didibus** [comment]
Ah ok, makes sense.
